### ISSUE TITLE
NoMethodError 'call' for for #<ColissimoLabel::GenerateLabel:0x007f8de9fe3ea8>

### ISSUE THREAD

**Issue by jbultez** [floXcoder/colissimo_label#1]
Hello,

Thanks for your gem, I tried it and got error when calling it in my method model.

NoMethodError - undefined method `call' for #<ColissimoLabel::GenerateLabel:0x007f8de9fe3ea8>

Your gem is require in my model with : 
- `  require 'colissimo_label'`

The http gem is installed to and require in my file

Have you already get this error before ? 

Thanks

**Comment by floXcoder** [comment]
Hello,

Sorry there was a mistake in the README. The correct method to call is `perform`.

I release a new version with the correct README.
